### ISSUE TITLE
Node detection is broken

### ISSUE THREAD

**Issue by Dietr1ch** [lamdu/lamdu#100]
I can't build lamdu because when building node (or figuring out
that it's not required), some python script fails

This is what I did,
```sh
sh -c "which node"
```
> /usr/bin/node

```sh
sudo pacman -S leveldb glfw libxrandr libxi libxcursor libxinerama
git clone --recursive https://github.com/lamdu/lamdu
cd lamdu
stack setup
stack install
```

> Progress 8/67
> --  While building custom Setup.hs for package nodejs-exec-0.1.0.0 using:
> /home/dietr1ch/Projects/lamdu/.stack-work/downloaded/I8OLPRN45ejO/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1 build lib:nodejs-exec --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics
> -color=always"
> Process exited with code: ExitFailure 1
> Logs have been written to: /home/dietr1ch/Projects/lamdu/.stack-work/logs/nodejs-exec-0.1.0.0.log
> Preprocessing library for nodejs-exec-0.1.0.0..
> Building library for nodejs-exec-0.1.0.0..
> Building nodejs from source
> fatal: destination path 'node' already exists and is not an empty directory.
> Please use either Python 2.6 or 2.7:
> (...)

At the end of the logs the following python2 line fails,
```py
print '%(major)s.%(minor)s.%(patch)s'% locals()
```

The error seems pretty silly, the `%` operator has nothing to replace and
there's a missing space before it.
I don't really know where does the file comes from to fix nor how the correct
format looks like, although it should just take a few compilation failures to figure.

**Comment by Dietr1ch** [comment]
NVM, the line works just fine on python2.
The issue is that it's not valid python3 and someone is assuming
that `which python` points to python2

**Comment by Dietr1ch** [comment]
Yep, the following temporary hack makes it work again (it's still compiling :( ),
```fish
ln -s (which python2) ~/.bin/python 
```

Now, I'm not sure why the install compiled node when I already had it installed.

**Comment by Dietr1ch** [comment]
Well, it seems lamdu doesn't build from master :/

> Building executable 'lamdu' for Lamdu-0.1..
> [1 of 1] Compiling Main             ( src/Lamdu/Main.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.2.0.1/build/lamdu/lamdu-tmp/Main.o )
> src/tcmalloc.cc:332] Attempt to free invalid pointer 0x233ff00
> Completed 39 action(s).

**Comment by yairchu** [comment]
With regard to the first issue - which version of nodejs did you have installed? Lamdu will build it from source if your version is 8.0.0 or newer (due to node's removal of tail calls supports), and I've just corrected the readme to reflect that.

Regarding the crash during compilation - this is a repeating problem on Arch (https://github.com/lamdu/lamdu/issues/51) - stack's provided GHC crashes when it makes use of a lot of memory :/
Could you try to build with nix and update on whether that works for you? (If it does then we'll change the Arch instructions to use nix)

**Comment by Dietr1ch** [comment]
I have node 10.4.0, so I guess its fine to build node.

I don't think the issue us about using a lot of memory, as it happens when
freeing some non-null pointer, though it might be uninitialized and not set
because some allocation failed.
Also at the time ghc-8.4.2 aborts it doesn't seem to be using a lot of memory,
memusage says it's peaking a total of 200kB on the heap.

I tried building with `stack build -j1` and it still fails, I'll just try using nix now.

**Comment by Dietr1ch** [comment]
Well, the build failed using nix too,

```fish
nix-env -f default.nix -iA lamdu
```
> [221 of 252] Compiling System.Remote.Monitoring.Shim ( src/System/Remote/Monitoring/Shim.hs, dist/build/System/Remote/Monitoring/Shim.o )
> src/System/Remote/Monitoring/Shim.hs:26:1: error:
> • ‘Server’ has no constructors (EmptyDataDecls permits this)
> • In the data declaration for ‘Server’
> |
> 26 | data Server
> | ^^^^^^^^^^^
> [222 of 252] Compiling System.TimeIt.Pure ( src/System/TimeIt/Pure.hs, dist/build/System/TimeIt/Pure.o )
> builder for '/nix/store/1hp5m2c7hhbi9k9z90gsq5jivsnsxfhw-Lamdu-0.1.drv' failed with exit code 1
> error: build of '/nix/store/1hp5m2c7hhbi9k9z90gsq5jivsnsxfhw-Lamdu-0.1.drv' failed

**Comment by yairchu** [comment]
Oh, well I pushed a fix for this now. Can you try again?

**Comment by Dietr1ch** [comment]
Thanks. Building with nix fails differently at `c8b5d8695` with some types not
being deduced

> [237 of 252] Compiling Lamdu.Sugar.Convert.Composite ( src/Lamdu/Sugar/Convert/Composite.hs, dist/build/Lamdu/Sugar/Convert/Composite.o )
> src/Lamdu/Sugar/Convert/Composite.hs:198:14: error:
> • Could not deduce (Semigroup a) arising from a use of ‘<>’
> from the context: (Monad m, Monoid a)
> bound by the type signature for:
> convert :: forall (m :: * -> *) a.
> (Monad m, Monoid a) =>
> (T.Tag -> ValI m -> T m (DataOps.CompositeExtendResult m))
> -> V.Leaf
> -> (T.Tag -> ValI m -> ValI m -> ValBody m)
> -> BodyPrism m a
> -> ExpressionU m a
> -> ExpressionU m a
> -> Input.Payload m a
> -> ExtendVal m (Input.Payload m a)
> -> ConvertM m (ExpressionU m a)
> at src/Lamdu/Sugar/Convert/Composite.hs:(177,1)-(183,67)
> Possible fix:
> add (Semigroup a) to the context of
> the type signature for:
> convert :: forall (m :: * -> *) a.
> (Monad m, Monoid a) =>
> (T.Tag -> ValI m -> T m (DataOps.CompositeExtendResult m))
> -> V.Leaf
> -> (T.Tag -> ValI m -> ValI m -> ValBody m)
> -> BodyPrism m a
> -> ExpressionU m a
> -> ExpressionU m a
> -> Input.Payload m a
> -> ExtendVal m (Input.Payload m a)
> -> ConvertM m (ExpressionU m a)
> • In the second argument of ‘(<>~)’, namely
> ‘(exprPl ^. Input.userData
> <> restS ^. annotation . plData . pUserData)’
> In the second argument of ‘(<&>)’, namely
> ‘annotation . plData . pUserData
> <>~
> (exprPl ^. Input.userData
> <> restS ^. annotation . plData . pUserData)’
> In the expression:
> convertExtend cons op valS exprPl extendV r <&> (prism #)
> >>= addActions [] exprPl
> <&> annotation . plEntityId .~ restS ^. annotation . plEntityId
> <&>
> annotation . plData . pUserData
> <>~
> (exprPl ^. Input.userData
> <> restS ^. annotation . plData . pUserData)
> |
> 198 |             (exprPl ^. Input.userData <> restS ^. annotation . plData . pUserData)
> |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by yairchu** [comment]
This has to do with our transition to GHC 8.4.x, which apparently isn't reflected in the nix build..

**Comment by bmabsout** [comment]
Same here, I tried messing a bit with the nix build replacing `haskellPackages` with `haskell.packages.ghc843` and updating the pinned nixexprs but ran into other errors: the imagemagick haskell library doesn't build on nixos-unstable apparently.

**Comment by yairchu** [comment]
@Dietr1ch @bmabsout:
The Nix build might be fixed now (fixed by @Peaker, am afraid I can't try because nix haskell builds don't seem to work on macOS which is my env), can you try again?

**Comment by Dietr1ch** [comment]
Apparently it builds, but fails installing on my machine.

```
nix-env -f default.nix -iA lamdu
installing 'Lamdu-0.1'
warning: dumping very large path (> 256 MiB); this may run out of memory
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied
```

I'd guess it's something wrong with my setup, bit I don't know what.
I'm using Manjaro with `aur/nix 2.0.2-2` and installing as a regular user
through the nix daemon (I saw nixbld1 doing all the work).

**Comment by ysangkok** [comment]
@Dietr1ch can you build https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/hello/default.nix ?

**Comment by bmabsout** [comment]
Worked for me! thanks

**Comment by yairchu** [comment]
Ok, so the original issue regarding the nodejs version is fixed, the other issue with stack's ghc being broken on arch linux is worked around with the nix build working there instead.
So if I understand correctly this issue can now be closed 👍

**Comment by Dietr1ch** [comment]
@ysangkok I fixed my nix setup. I was able to install hello and lamdu. However, it fails to start
with a segfault after failing to load anchors.js,

```
lamdu: user error (Failed to decode: "Error: Cannot find module 'anchors.js'")
fish: “lamdu” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by yairchu** [comment]
@Dietr1ch are you running it from its root path? It looks like maybe we currently have problems running it from other paths.

**Comment by yairchu** [comment]
> How reproducible is the nix build?

Not so much I'm afraid. We've been using mostly `stack`. I'm on macOS where afaik nix based builds for Haskell projects don't work.
The nix build has been contributed by @razvan-panda, and in order to keep it update and not break it when we update the stack based build we've added a [test](https://github.com/lamdu/lamdu/blob/master/test/TestNix.hs) to verify that changes in `stack.yaml` get reflected in the nix build, but we don't really test it [nor use in continuous integration](https://github.com/lamdu/lamdu/issues/97)..
