### ISSUE TITLE
Configure GHC version in Nix build

### ISSUE THREAD

**Issue by yairchu** [lamdu/lamdu#101]
Find out how to specify GHC version in the nix build and check in TestNix that the version matches to the one from the `stack` based build..

See #100

**Comment by Dietr1ch** [comment]
This might be interesting, https://github.com/NixOS/nixpkgs/pull/15989

**Comment by yairchu** [comment]
Solved in https://github.com/lamdu/lamdu/commit/16a5f86309e8af0aa5bb0d2c2fc7e31bfe694e3a, right?

**Comment by Peaker** [comment]
Yes
