### ISSUE TITLE
Optimize Travis build / Make better use of caching

### ISSUE THREAD

**Issue by yairchu** [lamdu/lamdu#102]
After updating `stack`'s resolver, Travis's cache is invalid and a full rebuild is done, but that doesn't finish there in under 25 minutes so the build fails, and apparently there's no caching of results from failed builds so it can't work again..
Need to figure out how to solve it, by example by working around it via enabling caching on failed builds on triggering a build with longer timeout when cache is invalidated..

**Comment by yairchu** [comment]
Depending on luck, after a few spurious failed builds a successful one happens and then iiuc caching will work.

**Comment by bjorn3** [comment]
Would it be possible to change .travis.yml to kill stack just before the timeout and let it return without error after that in one commit and then push a revert commit?

**Comment by yairchu** [comment]
@bjorn3 that's possible I guess.
Maybe we should have a script that creates a commit with your suggested change to `.travis.yml` and pushes it to a `travis-workarounds` branch which Travis will build.

**Comment by yairchu** [comment]
Travis now uses the nix build since https://github.com/lamdu/lamdu/commit/de57b04adccb3e7afc57ae3aded7d7cf7e214a2d

Should see after next commit how long incremental builds take / how good is the caching.

**Comment by yairchu** [comment]
Will move from Travis to GitHub Actions, so no point in improving the Travis setup
