### ISSUE TITLE
Suggestion for contributor documentation improvement

### ISSUE THREAD

**Issue by e3b0c442** [lamdu/lamdu#108]
Good day,

As a potential contributor to this project, I found that locating information on how to contribute and be a part of the project community was more difficult than it needed to be because information on contributing to the project was not available in some of the well known/standard places for open source projects hosted on GitHub.

I would like to suggest either (or both of) a CONTRIBUTING.md file be added to the repo with at least the information contained on the "Contributors wanted!" section of the project homepage, and/or this information or a direct link to it be added to the README.md which is frequently going to be the first contact page for people that might be looking to contribute.

Thank you for considering this suggestion.

**Comment by yairchu** [comment]
Good idea!

Is there an example for a good `CONTRIBUTING.md` file that you think we can take inspiration from?
I tried looking for one in various dependencies of lamdu like https://github.com/ekmett/lens/ https://github.com/Lysxia/generic-data/ or tools we use like https://github.com/ndmitchell/hlint/ and hadn't found one.

**Comment by e3b0c442** [comment]
Honestly, I think it could be something just as simple as the same statement that's on the project website, directing people to the chat room, if that's how you want people to start getting involved. From my perspective, it's less about the specific content than the location. One thing to keep in mind is that if you have a CONTRIBUTING or CONTRIBUTING.md file, GitHub has a special UI that calls attention to it at the top of the issues page, à la the [Rails issue page](https://github.com/rails/rails/issues).

If you wanted something more formal, [GitHub offers some guidance](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) along with some examples from larger projects; there are [a](https://gist.github.com/PurpleBooth/b24679402957c63ec426) [few](https://mozillascience.github.io/working-open-workshop/contributing/) [guides and examples](https://embeddedartistry.com/blog/2017/12/11/get-others-involved-in-your-project-with-a-contributing-guide) around too. 

I personally like the Go CONTRIBUTING.md (though, amazingly, it isn't actually in their GitHub repo) -- it is concise with some bullet points covering the basics, with links to more in-depth documentation as required.

**Comment by yairchu** [comment]
I added an initial `CONTRIBUTING.md` file. I don't see the same UI as in the Rails issue page, but perhaps that's because I'm already a contributor? Do you see it?

**Comment by e3b0c442** [comment]
Yes, I can verify through a different account that hasn't submitted an issue or made a contribution that the UI appears as expected.

CONTRIBUTING.md looks great, thanks for taking my suggestion!
