### ISSUE TITLE
Crash on tutorial flow

### ISSUE THREAD

**Issue by luqui** [lamdu/lamdu#113]
I tried the tutorial, and it worked well.  But then I tried to do one more thing and it crashed.

Follow tutorial up until naming, name the variable `phi`, then in the body of the let, select `phi` and type `^2-p` (with the intention of later typing `hi`, but it crashes at this point for me)

The error is

    Main exiting due to exception: Prelude.tail: empty list

The error persists if I try to open lamdu again until I wipe `~/.lamdu`

MacOS 10.15.7

**Comment by yairchu** [comment]
One "cheat" for working around such cases without losing your work `lamdu undo 1`

**Comment by yairchu** [comment]
Problem reproduces for me too, thanks for reporting!

<img width="489" alt="Screen Shot 2021-01-07 at 21 53 28" src="https://user-images.githubusercontent.com/97606/103938428-de04c000-5132-11eb-83b2-18276b71c1dd.png">

**Comment by yairchu** [comment]
Should follow up with a test for this, and also investigate another regression seen here, where the values in the let-body aren't showing up..
