### ISSUE TITLE
Typo in the tutorial?

### ISSUE THREAD

**Issue by gvnnz** [lamdu/lamdu#115]
In the [Creating a function tutorial](https://github.com/lamdu/lamdu#creating-a-function), the `factorial` function is first mentioned. Then, later on, the same function is referred to as `fac` in `if x=0 1 x*fac(x-1)` . Should it be `if x=0 1 x*factorial(x-1)` instead? The same also for the bullet point 
> Type "fac 5" and press space.

**Comment by yairchu** [comment]
Did you try typing it like the tutorial? Did it work? It's supposed to be a demonstration of completions rather than a typo.

**Comment by gvnnz** [comment]
I figured out the problem: I was using the Linux executable from lamdu.org and for some reason I couldn't type the `(` symbol. Lamdu compiled from source (latest master) works fine.
