### ISSUE TITLE
Release 0.8 macOS app says it's version 0.6

### ISSUE THREAD

**Issue by danra** [lamdu/lamdu#130]
<img width="629" alt="Screen Shot 2021-09-10 at 18 48 47" src="https://user-images.githubusercontent.com/84245/132881569-f11e2ace-e439-45cb-a17b-b3d226d7522a.png">

**Comment by yairchu** [comment]
Ooh, so I guess there's a `.plist` which needs updating and we should add test to verify it

**Comment by yairchu** [comment]
Now there's a test to catch this. A better solution might be to have a single source of truth but this will do for now :)
