### ISSUE TITLE
Question about higher order function

### ISSUE THREAD

**Issue by DrDub** [lamdu/lamdu#138]
I read the language description under docs and I don't quite understand what am I doing wrong here or what is missing. Any help would be appreciated:

![image](https://user-images.githubusercontent.com/315403/146480715-2a5424dc-484d-4869-8f9f-28c888d87407.png)

I'm just trying to make something like this (using Haskell syntax, I understand Lamdu is not Haskell):
 
```haskell
dup f = f . f
times2  = (*) 2
dup times2 5
```

**Comment by EyalIO** [comment]
The argument being given to dup is not times2, but times2 applied to a hole. This is a type mismatch so a fragment denoted by a question mark wraps the "times2 _" expression.

You can delete the hole after times2 to remove the function application.

As an aside, you can also press ctrl-v, on the use of x0 to remove the intermediate variable.

**Comment by DrDub** [comment]
Thanks, that worked.

![image](https://user-images.githubusercontent.com/315403/146485416-958baa3d-3072-4687-a6f9-9629b9eb53ad.png)

The hole in times2 _ came about by selecting times2 from the drop-down menu. Wouldn't that be a type inference error?

**Comment by EyalIO** [comment]
> The hole in times2 _ came about by selecting times2 from the drop-down menu. Wouldn't that be a type inference error?

The drop-down menu is a the "hole results".

Hole results are a work in progress, we're trying to design them to be ergonomic, but there are a lot of constraints at play:
* Predictability (So you can type quickly without interactivity)
* Responsiveness (Can't type-check every possible result before offering completions)
* Usefulness (Optimize the common case even at the expense of less common cases)

And more...

In any case, I think we should not auto-apply functions in hole results anymore, but instead allow "space"(function application in wytiwys(what-you-type-is-what-you-see) form) on the hole result to apply it.

So this:
![image](https://user-images.githubusercontent.com/19535321/146524595-1526098b-2dce-4ee5-8e0f-f60b07915fa9.png)

should be offerred unapplied (cc @yairchu)

**Comment by DrDub** [comment]
Makes sense. You solved my original problem (thanks!). If this issue helps you track progress on that feature, maybe rename it? Otherwise I'm fine with closing it.

**Comment by yairchu** [comment]
If we look at the equivalent in Visual Studio Code and Rust,

clicking "enter" here:

<img width="912" alt="Screen Shot 2021-12-19 at 17 46 29" src="https://user-images.githubusercontent.com/97606/146681279-f69cde28-efdb-494b-b9da-e0ee74930fe1.png">

results with:

<img width="608" alt="Screen Shot 2021-12-19 at 17 46 56" src="https://user-images.githubusercontent.com/97606/146681290-795eafa4-53d8-4f3a-9dc5-95d110b30140.png">

Indeed in this case I'd go and erase the extraneous completion. But it appears that this is the choice many editors (also Xcode) made, although mostly for non-functional languages. We could not apply it if it infers better but that would be less predictable.

**Comment by EyalIO** [comment]
I think we can be predictable: always not-apply it.

"<space>" on the result already means to select&apply?
