### ISSUE TITLE
Possibly incorrect translations for floor and ceil?

### ISSUE THREAD

**Issue by yairchu** [lamdu/lamdu#140]
I noticed this due to knowing just enough Spanish to know what "aproximado" is :)

<img width="341" alt="Screen Shot 2021-12-19 at 17 00 41" src="https://user-images.githubusercontent.com/97606/146679741-5590ca3e-0cb1-41f5-8a46-f15686fd48ce.png">

<img width="684" alt="Screen Shot 2021-12-19 at 17 00 57" src="https://user-images.githubusercontent.com/97606/146679756-db255b3e-fc2a-445d-a686-faf15bced266.png">

<img width="677" alt="Screen Shot 2021-12-19 at 17 00 49" src="https://user-images.githubusercontent.com/97606/146679746-20253c6d-c486-4205-ba50-e7f68329fa05.png">

Looks like in a8ad9458c8e2ff129b8096fb05cc55fe12b1a5a4 @gvnnz translated "ceil" to "arrontada", which iiuc is "round" rather than "ceil". Advising with Google Translate perhaps it should be "arrotondaPerEccesso" ("round up")?

The Spanish was derived from the Italian, so it propagated this translation.
According to Google translate floor/ceil or round down/up would be "redondear hacia abajo/arriba" or maybe "piso/tope"? @DrDub could you advise what would be preferred?

**Comment by DrDub** [comment]
You are correct. redondearHaciaAbajo redondearHaciaArriba ought to be preferred as they are how we speak it and are clear and unambiguous. "piso"/"techo" would be understood for people knowing the English but the point is to make it accessible to people who don't know English.

**Comment by yairchu** [comment]
> You are correct. redondearHaciaAbajo redondearHaciaArriba ought to be preferred as they are how we speak it and are clear and unambiguous. "piso"/"techo" would be understood for people knowing the English but the point is to make it accessible to people who don't know English.

Thanks for the advise!
