### ISSUE TITLE
Nominals should have separate disambiguation tags namespace

### ISSUE THREAD

**Issue by yairchu** [lamdu/lamdu#141]
The nominal constructor "Maybe" needn't get a disambiguation tag here:

<img width="507" alt="Screen Shot 2021-12-30 at 16 18 08" src="https://user-images.githubusercontent.com/97606/147759933-5381b14e-ed7d-4ee4-8c9e-c08b2b4ac26f.png">

This should only happen when there are two nominals with the same name! Because the usage as a nominal constructor is already disambiguated from variables called "maybe".

**Comment by Peaker** [comment]
It was because we decided that if a name is ambiguous it'll be
disambiguated everywhere always.

But I guess that was oversimplified too

**Comment by yairchu** [comment]
Fixed!
