### ISSUE TITLE
Nitpicks

### ISSUE THREAD

**Issue by Peaker** [lamdu/lamdu#158]
* Nested destructuring does not trigger if the same tags exist in the two record levels. Allowing them to trigger exposes that we do not have name disambiguation and also have clashing anim ids

* ~red cursor when pressing `:` at the cursor there:~
![image](https://user-images.githubusercontent.com/48899/154367713-a8152319-51b9-4678-a270-917079d6738b.png)

* ~Indent whole definition body when it is under the definition assignment~

* ~When case alts / record fields do not fit in a line, indent them so the name length does not affect the whole width~

* ~by pressing space when selecting encode it adds a second field rather than an arg.
if choosing it with enter and then pressing space it does add an arg:~
![image](https://user-images.githubusercontent.com/48899/154367921-07b82325-b1b1-43ec-86a0-f155b19a1927.png)

* ~A fragment record value with a known type, when typing "." has duplicate results for the getfields~
![image](https://user-images.githubusercontent.com/48899/154368086-ddc80591-8a9b-4393-8344-c84060c2e590.png)

* ~Comma when choosing case tag should add field at the end and with clear search text~

* ~Comma when choosing record tag should add another field~

**Comment by yairchu** [comment]
Layout updates - in the first record "dir" the value is indented as it wouldn't fit on the right.

<img width="637" alt="Screen Shot 2022-02-18 at 23 47 58" src="https://user-images.githubusercontent.com/97606/154765800-a1165a37-cd1b-4ddb-a179-932a1d57948e.png">

**Comment by Peaker** [comment]
In the `{encode count}` issue, where "space" is ambiguous (add destructured arg VS add arg to the parameter), maybe it would be resolved if we add commas for destructuring? And use comma for both record structuring and de-structuring?

**Comment by yairchu** [comment]
> In the `{encode count}` issue, where "space" is ambiguous (add destructured arg VS add arg to the parameter), maybe it would be resolved if we add commas for destructuring? And use comma for both record structuring and de-structuring?

Can try it, but I fear it might be a bit uglier.. Also note that for punned record fields we don't separate with commas. I kind of like how clean things look

**Comment by yairchu** [comment]
If removing the `hasDups` check in `convertRecordParams` then this now works:

<img width="535" alt="Screen Shot 2022-02-20 at 17 31 07" src="https://user-images.githubusercontent.com/97606/154850388-d25a7a62-0aac-4d35-bbbf-de2c2c003779.png">

Screenshot reveals missing ordering in nested params though (will fix)

**Comment by yairchu** [comment]
all nitpicks fixed :)

**Comment by Peaker** [comment]
Awesome work! :-)
