### ISSUE TITLE
Perhaps "type variable escape" should be presented differently?

### ISSUE THREAD

**Issue by Peaker** [lamdu/lamdu#166]
Example type error:

![image](https://user-images.githubusercontent.com/48899/154908059-77a7e033-a7e0-46bd-bc33-6ced23d08cfe.png)

It's not very clear...
Perhaps the escaping variable should be highlighted somehow with some information tooltip popping with a web link to an explanation (like Rust compilation errors?)

**Comment by yairchu** [comment]
Fixed in 0f6969a5ac082e606b4210c8cee5d12de694fe87

<img width="820" alt="Screenshot 2023-09-18 at 16 46 42" src="https://github.com/lamdu/lamdu/assets/97606/76d40735-aa7a-45a3-9499-2162007d5055">
