### ISSUE TITLE
exit due to exception

### ISSUE THREAD

**Issue by AndreaBressan** [lamdu/lamdu#183]
I have built lamdu on voidlinux using stack without issue, but it exits with a message about the compression library snappy. Can you help?
I tried both the master branch and the v0.8.1 tag.  The result of running lamdu is:

$ lamdu
Lamdu 0.8.1

Main exiting due to exception: user error (open: Invalid argument: Compression type Snappy is not linked with the binary.)

**Comment by yairchu** [comment]
Can you try to run the tests of [`rocksdb-haskell`](https://github.com/serokell/rocksdb-haskell)? Do they give the same error?

**Comment by AndreaBressan** [comment]
Thanks for looking into it, I am currently away and I'll run the tests next month when I'll be back.

**Comment by AndreaBressan** [comment]
Probably it was a packaging issue in the rocksdblib. I retried after updating and it runs. Thanks
