### ISSUE TITLE
UI does not contain shell

### ISSUE THREAD

**Issue by J3RN** [lamdu/lamdu#220]
Hello!  I've heard a lot about Lamdu, and am trying it for the first time today.

I downloaded the tarball for Linux, untarred it, and started Lamdu with `./run-lamdu.sh`.  The window opens, but I wasn't really sure where to go from there.  The README states:

> ### Simple Expressions
> At the top we have an interactive shell, where we can type calculations.

Here is what my window looks like (well, after I defined a `factorial` function in it): 
![image](https://github.com/lamdu/lamdu/assets/2058614/c17009e6-45b5-4843-8f67-6245826360cb)

I don't see a shell or prompt or anything.  What am I missing?

**Comment by yairchu** [comment]
Fixed the tutorial. Please feel free to re-open if it still doesn't work.

**Comment by yairchu** [comment]
And thanks for reporting! :)
