### ISSUE TITLE
[Bug] README typo

### ISSUE THREAD

**Issue by maren-cole** [lamdu/lamdu#232]
**Bug Description**
Typo in the "Tutorial" section of the README.

**Website Address**
https://github.com/lamdu/lamdu/blob/main/README.md

**Steps To Reproduce**
Navigate to lamdu/README.md
Navigate to the second bullet point under tutorial / simple expressions / To type the calculation above

**Expected Behavior**
Expected spelling : "Hit space to choose your selected menu option"

**Actual Behavior**
Actual spelling : "Hit space to chose your selected menu option"

**Comment by maren-cole** [comment]
I am new to this project, but I would like to address this little typo. I can submit a pull request by end of day. Thanks!

**Comment by yairchu** [comment]
Thanks :)
