### ISSUE TITLE
better "type classes" for Lamdu - Easier for everyone ? (for app dev && for lambdu dev)

### ISSUE THREAD

**Issue by rvion** [lamdu/lamdu#24]
http://www.haskellforall.com/2012/05/scrap-your-type-classes.html
Lamdu seems perfect for easing such design pattern.

Is that something you considered ?

**Comment by Peaker** [comment]
On second thought, it might be possible to give type-level names for instances and index types by those, but type-classes aren't going to be implemented very soon :)

**Comment by Peaker** [comment]
In https://www.youtube.com/watch?v=hIZxTQP1ifo, Edward kmett makes a compelling argument why indexing types on their instances is not a great solution in the general case.

It is quite convincing that Haskell-style type-classes are a very desirable feature.
