### ISSUE TITLE
Lamdu language specification/examples

### ISSUE THREAD

**Issue by minad** [lamdu/lamdu#39]
Hi,

this is an interesting editor that you are working on! Do you specify somewhere the features of the lamdu language? I would like to see some examples of the supported Haskell subset. Do you plan to support adhoc polymorphism (via typeclasses, modular implicits, ...)? And what about dependent types?

Daniel

**Comment by int-index** [comment]
Here are some quotes by @Peaker 

>  Our language has a structural type system (row polymorphism, column polymorphism/polymorphic variants, and nominal types as well)

> We started with DT's, we weren't type experts enough to get it to work well :) Too much research-y aspects killed us, so we decided to put that part aside.

> We do hope to someday have DT's, but not in the foreseeable future.

**Comment by gitfoxi** [comment]
Yeah, I can't get anywhere with it. There's a TUTORIAL file which suggests I type something like:

Type this line into the Editor slowly, key-by-key, including
spaces, and examine what happens after each key stroke:

    fac x=if x=0 1 x*f x-1

I get as far as

    fac x=if

Before it says `(No results)` and won't accept further input

**Comment by Peaker** [comment]
Ooh the tutorial is far out of date, will update soon, thanks!

**Comment by Peaker** [comment]
Thanks for the report!

The tutorial is very out of date, will rewrite one soon.

On Tue, Nov 17, 2015 at 11:40 PM, Chiciuc Nicușor <notifications@github.com>
wrote:

> Hi, I just found about this project. Installed everything without problems
> but I'm stuck because there isn't any easy available tutorial. Also in your
> tutorial I stop at the if statement because (No results).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lamdu/lamdu/issues/39#issuecomment-157517471>.
>



-- 
Eyal

**Comment by yairchu** [comment]
Added an updated tutorial in the main README.md.
Please try this one instead and keep us posted if there are still problems.
Thx!

**Comment by nicu-chiciuc** [comment]
Thanks, I'll take a look later this week.

**Comment by ysangkok** [comment]
[An Euler 3 solution](http://imgur.com/Y9qryWd.png ([archive](http://archive.li/P3D3n/6b9ced39b5a6e499f1e3cbc5c78f6a72c04ee5fe.png))) was posted on Hacker News. Here is [an explanation](https://news.ycombinator.com/item?id=11149176) ([archive](https://archive.is/Kq1Tk)) .

**Comment by yairchu** [comment]
I created a document describing the [high-level "sugared language"](https://github.com/lamdu/lamdu/blob/master/doc/Sugar.md) which also briefly describes and links to the underlying lower level calculus.
