### ISSUE TITLE
How to run lamdu?

### ISSUE THREAD

**Issue by jkleiser** [lamdu/lamdu#47]
I have installed lamdu on OSX (10.11.2) as described in the README.md, and there was no errors that I could see. How do I now run lamdu?

**Comment by yairchu** [comment]
Does typing `lamdu` in the shell work? What about `~/.local/bin/lamdu`?

**Comment by jkleiser** [comment]
Thanks. I found lamdu in ~/.local/bin/, but when I run it, I get this:
```
$ .local/bin/lamdu
Main exiting due to exception: MissingFont "/Volumes/P3/Lamdu/lamdu/.stack-work/install/x86_64-osx/nightly-2015-12-17/7.10.3/share/x86_64-osx-ghc-7.10.3/Lamdu-0.1/fonts/Purisa.ttf does not exist!"
```
I see that only DejaVuSans.ttf is found in that directory, but if I copy in the other fonts, then lamdu starts up.
The first time I did Quit from the lamdu menu, I got this:
```
lamdu(48657,0x7fff7637d000) malloc: *** error for object 0x4000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
Afterwards, it did not happen.
Now it remains to see if I can figure out how to use lamdu. ;-)

**Comment by yairchu** [comment]
Oh, we lately added some fonts and did not update the cabal file. Now that problem should be fixed

**Comment by yairchu** [comment]
Alright, now added to the instructions to run it from ~/.local/bin
Thanks!
