### ISSUE TITLE
Key binding for Mac?

### ISSUE THREAD

**Issue by eccstartup** [lamdu/lamdu#50]
I just compiled it successfully. But I think the key binding for Mac OS X not very comfortable. Is there a possible change?

I mean that `F1` is `Fn + F1` for most people. I also mean that `Command` key is not widely used in this program.

**Comment by Peaker** [comment]
Perhaps you can contribute a config.json file with the key bindings appropriate for Macs?

We can later hook up the correct json file for each platform.

**Comment by yairchu** [comment]
Done. Now on macOS Cmd+Z works for undo, Cmd+Q for quit, etc everything that was with Ctrl..
