### ISSUE TITLE
lamdu: Unknown Prelude function sqrt

### ISSUE THREAD

**Issue by kanelbulle** [lamdu/lamdu#53]
1. Open lambdu
2. Type (without quotes): "1+s"
3. See the auto complete with "sqrt at top"
4. Hit enter

Crashes:

´´´
~/.local/bin/lamdu
lamdu: Unknown Prelude function sqrt
Main exiting due to exception: Unknown Prelude function sqrt
´´´

**Comment by yairchu** [comment]
Oops, we broke it..
Pushed a fix, please try again now, thanks!
