### ISSUE TITLE
Error on startup "Inexistent guid: repl referenced" due to old DB, segfault after deleting DB

### ISSUE THREAD

**Issue by mgsloan** [lamdu/lamdu#57]
```
mgsloan@computer:~/oss/Peaker/lamdu$ lamdu
Main exiting due to exception: user error (Inexistent guid: repl referenced)
mgsloan@computer:~/oss/Peaker/lamdu$ lamdu -deletedb
Deleting DB...
mgsloan@computer:~/oss/Peaker/lamdu$ lamdu
Segmentation fault (core dumped)
```

I did successfully run an old lamdu in the past, which is probably the cause of the first error.  Reflog reveals that I was on https://github.com/lamdu/lamdu/commit/848bcc5

**Comment by Peaker** [comment]
Seg faults usually relate to the font library and rarely in leveldb.

If it is somehow related to the old db you can use the -deletedb flag.

**Comment by mgsloan** [comment]
Oddly enough, after recompiling with profiling (in this case, `stack build --trace` to get `-xc` traces), the problem disappeared.
