### ISSUE TITLE
Any tips for installing on Arch Linux

### ISSUE THREAD

**Issue by ChristopherKing42** [lamdu/lamdu#59]
Anyone know how to install this on Arch Linux?

**Comment by mgattozzi** [comment]
Looks like you need to find the equivalent packages. They're usually named differently. For instance, Ubuntu has libxrandr-dev but Arch Linux always packages the libraries and binary in one. All you would need to do in this case is pacman -S xrandr. I'm not sure what the equivalent of all the other packages is but that shouldn't be too hard to look up.

**Comment by yairchu** [comment]
We don't have an Arch linux setup, but if you figure out how to do it we'd love a pull request to add the instructions to our README.

**Comment by ChristopherKing42** [comment]
@yairchu I'll take a look.

**Comment by faineance** [comment]
@ChristopherKing42 I've created a pr for arch linux instructions.

**Comment by yairchu** [comment]
@ChristopherKing42 did @faineance's instructions (now in the README) work for you?

**Comment by ChristopherKing42** [comment]
@yairchu I got this error (which is likely unrelated to Arch Linux)

```
$ cat ~/Haskell/lamdu/.stack-work/logs/Lamdu-0.1.log 
Configuring Lamdu-0.1...
Preprocessing library Lamdu-0.1...
In-place registering Lamdu-0.1...
Preprocessing executable 'lamdu' for Lamdu-0.1...
[  3 of 145] Compiling Lamdu.GUI.Precedence ( Lamdu/GUI/Precedence.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/lamdu/lamdu-tmp/Lamdu/GUI/Precedence.o )
src/tcmalloc.cc:278] Attempt to free invalid pointer 0x196b700 
```

**Comment by yairchu** [comment]
Looks like a compiler crash.. :/
Seems that Arch's Linux's GHC crashes when compiling Lamdu/GUI/Precedence.hs

This is the exact same error as here:
https://github.com/lamdu/lamdu/issues/51

**Comment by Peaker** [comment]
dup of #51
