### ISSUE TITLE
Problem installing Lamdu on Mac El Captain

### ISSUE THREAD

**Issue by gz4053** [lamdu/lamdu#63]
I wanna install lamdu but the terminal tells me

<command line>: cannot satisfy -package-id mtl-2.2.1-b6b36d751642fde56f037818eb788105

Does anyone know what the problem is and how to fix it

**Comment by yairchu** [comment]
Are you installing it using the instructions from the README, with stack?

**Comment by Peaker** [comment]
Closing -- if this problem persists, please reopen.
