### ISSUE TITLE
Can't delete definition on OS X

### ISSUE THREAD

**Issue by thSoft** [lamdu/lamdu#66]
Using OS X 10.11.4 and lamdu 8d0f8b13669da2a8d4b6ac89798aa58721e88bcc, I can't delete a definition with neither Delete nor Backspace. I can delete expressions within definitions, though.

**Comment by eladraz** [comment]
I also encountered the same problem. With latest Xcode installed Version 7.3 (7D175)

**Comment by ysangkok** [comment]
Known bug, see https://gitter.im/lamdu/lamdu?at=569508967669220736033ae5

**Comment by Peaker** [comment]
Can delete now (press del on a definition).

Since we have an "open world assumption" and version control, delete is not "actual" delete but a visible deprecation mark. It also filters out from hole results so it is very nearly "deleted".
