### ISSUE TITLE
lamdu.org has expired

### ISSUE THREAD

**Issue by yberreby** [lamdu/lamdu#70]
As of writing, [lamdu.org](http://lamdu.org) shows a landing page stating:

> This domain name expired on Aug 6 2016 04:18:47:000PM

You might want to update the link pointing to it in the README, or renew the domain.

**Comment by yairchu** [comment]
Oops, good catch! Just clicked renew and we should have it back soon.. Thanks so much. It seemed like I missed the email from the registrar..

**Comment by yberreby** [comment]
Always happy to help :)
