### ISSUE TITLE
Initialize failed

### ISSUE THREAD

**Issue by hchasestevens** [lamdu/lamdu#71]
After installing lamdu on a fresh Ubuntu 14.04 install, following the instructions listed in README.md, running
`~/.local/bin/lamdu`
results in:
```bash
# ~/.local/bin/lamdu
importing from: "/root/lamdu/freshdb.json"
Main exiting due to exception: user error (initialize failed)
```
Further attempts to run lamdu continue to result in `Main exiting due to exception: user error (initialize failed)`.

**Comment by yairchu** [comment]
Hmm, what happens if you run it from the source directory? Does it find "freshdb.json" successfully there?

**Comment by yairchu** [comment]
@hchasestevens does https://github.com/bsl/GLFW-b-demo work for you?

**Comment by hchasestevens** [comment]
Hi @yairchu ,

I haven't had a chance to test out https://github.com/bsl/GLFW-b-demo , but I have reproduced the issue I was seeing within a docker container, using the `ubuntu:latest` base image. Attached are the logs. The error was reproducible both when run from the home directory (line 5288) and from the source directory (line 5240). I would also be happy to export the container if it would help your debugging.

Thanks!
[lamdu-logs.txt](https://github.com/lamdu/lamdu/files/1405474/lamdu-logs.txt)

**Comment by Peaker** [comment]
Hi @hchasestevens, I assume your container is simply headless, and cannot open GUI windows?

If GLFW-b-demo does work, then there is a lamdu issue, in which case re-open the issue.
