### ISSUE TITLE
Black screen with green dots

### ISSUE THREAD

**Issue by vanschelven** [lamdu/lamdu#74]
I've installed the latest version of lamdu (3ff2c87ca6b0).

On starting, all I'm seeing is a dark grey screen with some green dots in the top left corner

Typing increases the number of pixels but not much else is achieved.
Clicking with the mouse I'm also able to see some red rectangles.

I'd love to help out in debugging the issue.

**Comment by yairchu** [comment]
Hmm, sounds very similar to the behavior mentioned [here](https://gitter.im/lamdu/lamdu?at=58ea837db52518ed4df5fd02)

Are you running inside a VM? Sounds like a problem in the font rendering due to some OpenGL weirdnesses..

@nickcollins did you find out anything about this problem?

**Comment by vanschelven** [comment]
Yes I'm running inside a VM (Ubuntu 14.04 on parallels on MacOS).

The pictures look quite similar to my situation

**Comment by nickcollins** [comment]
i didn't discover anything more. i got lamdu to work by running it on my friend's mac instead of inside my vm. Worth noting that my ubuntu 16.04 windows-hosted vm is only permitted 2GB of memory, so if @vanschelven 's VM is also memory throttled, maybe that's related. If it isn't, then maybe there's just some issue with the GL rendering on VMs

**Comment by yairchu** [comment]
So apparently Parallels is reporting a screen physical length/width of 0, as evident by the new info script https://github.com/lamdu/lamdu/blob/master/gui-examples/SysInfo.hs ...

I'll work around this shortly

**Comment by yairchu** [comment]
Pushed a fix https://github.com/lamdu/lamdu/commit/c96fcd9bc73817288678c941979cba3313a65f99,
could you check if it works now?

Btw, over here Lamdu looks better not via Parallels (with its default options at least), because Parallels emulates a lower display resolution on my laptop's display.

**Comment by vanschelven** [comment]
It works!

The resolution is fine.
