### ISSUE TITLE
Upgrade to node v6.11.3

### ISSUE THREAD

**Issue by ysangkok** [lamdu/lamdu#79]
Now that v6.11.3 has been released with GCC 7 compatibility, it would be nice to upgrade to it.

**Comment by yairchu** [comment]
Sure thing.
I see there is also ver 8 now. When we switched to [v6.2.2](https://github.com/lamdu/nodejs-exec/commit/bc982b8bb2e155e82d01b5843e29e0687b693182) that was the latest, should we be switching to version 8 instead? Does it also support GCC 7?
If node incorporated v8 speedups that would be a benefit too.

**Comment by ysangkok** [comment]
I am pretty sure the newest node would also work with GCC 7, the changes were backported from the newest v8 to their old branch.

Of course Node does incorporate v8 speedups, but they only switch minor v8 releases on major releases, AFAIK. I don't think the speed difference will be large if you switch to Node 8.

I think it makes sense to stay on an LTS release to minimize the maintenance burden.

**Comment by yairchu** [comment]
Alright, fixed in master now
