### ISSUE TITLE
Fails to run with "not enough bytes"

### ISSUE THREAD

**Issue by sinelaw** [lamdu/lamdu#83]
```
.stack-work/install/x86_64-linux/lts-10.0/8.2.2/bin/lamdu 
Using GL version: "3.0 Mesa 17.0.7"
Main exiting due to exception: Data.Binary.Get.runGet at position 16: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get

```

**Comment by Peaker** [comment]
We need to add an explicit version to our database, and output instructions on how to upgrade the DB when the schema changes.
cc @yairchu

**Comment by Peaker** [comment]
@sinelaw in the mean time, you can `lamdu deletedb` if you don't care about losing the data in there.

**Comment by yairchu** [comment]
Now Lamdu gives better errors/instructions when this happens. There's an explicit DB version and versions from before adding it get verified before being blessed.
