### ISSUE TITLE
Building on Fedora using Stack fails

### ISSUE THREAD

**Issue by razvan-panda** [lamdu/lamdu#86]
Following the instructions here: https://github.com/lamdu/lamdu#fedora

stack install failed with:

> --  While building custom Setup.hs for package digest-0.0.1.2 using:
>       /root/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0 configure --with-ghc=/root/.stack/programs/x86_64-linux/ghc-tinfo6-8.2.2/bin/ghc --with-ghc-pkg=/root/.stack/programs/x86_64-linux/ghc-tinfo6-8.2.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/pkgdb --libdir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/lib --bindir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/bin --datadir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/share --libexecdir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/libexec --sysconfdir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/etc --docdir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/doc/digest-0.0.1.2 --htmldir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/doc/digest-0.0.1.2 --haddockdir=/root/.stack/snapshots/x86_64-linux-tinfo6/lts-10.5/8.2.2/doc/digest-0.0.1.2 --dependency=base=base-4.10.1.0 --dependency=bytestring=bytestring-0.10.8.2 -f-bytestring-in-base --exact-configuration
>     Process exited with code: ExitFailure 1
>     Logs have been written to: /home/osboxes/Sources/lamdu/.stack-work/logs/digest-0.0.1.2.log
> 
>     Configuring digest-0.0.1.2...
>     Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: Missing dependency on a foreign
>     library:
>     * Missing (or bad) header file: zlib.h
>     * Missing C library: z
>     This problem can usually be solved by installing the system package that
>     provides this library (you may need the "-dev" version). If the library is
>     already installed but in a non-standard location then you can use the flags
>     --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
>     If the header file does exist, it may contain errors that are caught by the C
>     compiler at the preprocessing stage. In this case you can re-run configure
>     with the verbosity flag -v3 to see the error messages.

OS: Fedora 27

Building via nix-build worked just fine as expected.

**Comment by Peaker** [comment]
Seems like zlib-devel is missing from the list of dependencies in the instructions. I don't have Fedora so can't test the package name easily. Can you check which zlib-dev package needs to be installed and edit the instructions?

**Comment by razvan-panda** [comment]
I am not a Fedora user myself. And **it builds fine using Nix** so I would prefer to not spend more time on fixing failed stack builds. Stack is just not a reliable tool.

**Comment by yairchu** [comment]
I guess we got this error because the person making the Fedora instruction already had `zlib-devel` installed.
It's true that nix isn't vulnerable to such problems.
