### ISSUE TITLE
Runtime errors on Fedora

### ISSUE THREAD

**Issue by razvan-panda** [lamdu/lamdu#87]
As non-root:

> Segmentation fault (core dumped)

As root:

> No protocol specified
> Main exiting due to exception: user error (initialize failed)

**Comment by yairchu** [comment]
Is it a headless system or does it have X11 etc?

**Comment by razvan-panda** [comment]
It is not headless, it uses X11.
I tested it on Fedora 27 image from here: https://www.osboxes.org/fedora/

**Comment by yairchu** [comment]
Does this problem still occur on current versions?
Does [`GLFW-b-demo`](https://hackage.haskell.org/package/GLFW-b-demo) work on this machine?

**Comment by razvan-panda** [comment]
Sorry but I don't know and I am busy with other stuff. Maybe mark the issue with `help-needed` tag.
Lamdu works fine under NixOS.

**Comment by yairchu** [comment]
So closing for now, could re-open if the issue persists and someone encounters it.
Thanks for all the help!
