### ISSUE TITLE
Building on Arch Linux using Stack fails

### ISSUE THREAD

**Issue by razvan-panda** [lamdu/lamdu#89]
Following the instructions here: https://github.com/lamdu/lamdu#arch-linux

stack install failed with:

> --  While building custom Setup.hs for package nodejs-exec-0.1.0.0 using:
>       /home/osboxes/Sources/lamdu/.stack-work/downloaded/a0UJV6AYd1fH/.stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0 build lib:nodejs-exec --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
>     Process exited with code: ExitFailure 1
>     Logs have been written to: /home/osboxes/Sources/lamdu/.stack-work/logs/nodejs-exec-0.1.0.0.log
> 
>     [1 of 2] Compiling Main             ( /home/osboxes/Sources/lamdu/.stack-work/downloaded/a0UJV6AYd1fH/Setup.hs, /home/osboxes/Sources/lamdu/.stack-work/downloaded/a0UJV6AYd1fH/.stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0/setup/Main.o )
>     [2 of 2] Compiling StackSetupShim   ( /home/osboxes/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/osboxes/Sources/lamdu/.stack-work/downloaded/a0UJV6AYd1fH/.stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0/setup/StackSetupShim.o )
>     Linking /home/osboxes/Sources/lamdu/.stack-work/downloaded/a0UJV6AYd1fH/.stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0/setup/setup ...
>     Configuring nodejs-exec-0.1.0.0...
>     Warning: To use the 'default-language' field the package needs to specify at
>     least 'cabal-version: >= 1.10'.
>     Preprocessing library for nodejs-exec-0.1.0.0..
>     Building library for nodejs-exec-0.1.0.0..
>     [1 of 2] Compiling Paths_nodejs_exec ( .stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0/build/autogen/Paths_nodejs_exec.hs, .stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0/build/Paths_nodejs_exec.o )
>     [2 of 2] Compiling System.NodeJS.Path ( src/System/NodeJS/Path.hs, .stack-work/dist/x86_64-linux-ncurses6-nopie/Cabal-2.0.1.0/build/System/NodeJS/Path.o )
>     build_node.sh: line 8: node: command not found
>     Building nodejs from source
>     Cloning into 'node'...
>     Note: checking out 'dbce2ecab3614e128fe028751470f49a60f2e860'.
>     
>     You are in 'detached HEAD' state. You can look around, make experimental
>     changes and commit them, and you can discard any commits you make in this
>     state without impacting any branches by performing another checkout.
>     
>     If you want to create a new branch to retain commits you create, you may
>     do so (now or later) by using -b with the checkout command again. Example:
>     
>       git checkout -b <new-branch-name>
>     
> Checking out files: 100% (19863/19863), done.
>     Please use either Python 2.6 or 2.7:
>     
>       /usr/bin/python2 ./configure --prefix=/tmp
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>       File "tools/getnodeversion.py", line 20
>         print '%(major)s.%(minor)s.%(patch)s'% locals()
>                                             ^
>     SyntaxError: invalid syntax
>     Makefile:84: *** Missing or stale config.gypi, please run ./configure.  Stop.
>     cp: cannot stat 'node/node': No such file or directory

OS: ArchLinux 2017.08 KDE (64bit)

Building via nix-build worked just fine as expected.

**Comment by yairchu** [comment]
Weird, looks like it's running `python3` (the `print x` system is fine in `python2`) even though the command line appearing there says `python2`..

**Comment by yairchu** [comment]
Haven't made progress on troubleshooting it, but as `nix-build` reportedly works and as some time has passed and maybe things changed (with current `stack` version etc) I'll close this. If the problem persists we could re-open. Thanks for the report!
