### ISSUE TITLE
Adding fields to named tuples should be more straight forward.

### ISSUE THREAD

**Issue by NightRa** [lamdu/lamdu#9]
Adding fields to named tuples should be more straight forward.

I had to search for a really hard time that I should press 'A' to add a field to a named tuple.

Maybe pressing enter will enter tuple editing and then there is always one empty name field that can be filled in, and once it's edited, there should be another empty one, and when exiting the tuple, it should disappear if it hasn't been edited.

**Comment by Peaker** [comment]
Field order no longer matters.

Creating an "empty" field under the existing fields could be much more discoverable. Doing it in each record would be annoying for navigation.

Needs more deliberation.

**Comment by yairchu** [comment]
With the new WYTIWYS (what you type is what you see) paradigm, which is implemented for records, I think we can safely say this problem is solved now, right?
