### ISSUE TITLE
library naming preventing launch

### ISSUE THREAD

**Issue by VegaDeftwing** [lamdu/lamdu#94]
just built, attempting to run gives
```
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  255
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  152
  Current serial number in output stream:  153
```
output of 
`ls | grep radeon`
is
```
libdrm_radeon.so -> libdrm_radeon.so.1
libdrm_radeon.so.1 -> libdrm_radeon.so.1.0.1
libdrm_radeon.so.1.0.1
libvulkan_radeon.so
```
and `ls | grep dri`
```
dri
liblirc_driver.so -> liblirc_driver.so.0.3.0
liblirc_driver.so.0 -> liblirc_driver.so.0.3.0
liblirc_driver.so.0.3.0
librustc_driver-06c2a980331bacf7.so -> rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-06c2a980331bacf7.so
libxcb-dri2.so -> libxcb-dri2.so.0.0.0
libxcb-dri2.so.0 -> libxcb-dri2.so.0.0.0
libxcb-dri2.so.0.0.0
libxcb-dri3.so -> libxcb-dri3.so.0.0.0
libxcb-dri3.so.0 -> libxcb-dri3.so.0.0.0
libxcb-dri3.so.0.0.0
libxcb-xf86dri.so -> libxcb-xf86dri.so.0.0.0
libxcb-xf86dri.so.0 -> libxcb-xf86dri.so.0.0.0
libxcb-xf86dri.so.0.0.0
```
finally in /usr/lib/dri
```
i915_dri.so  kms_swrast_dri.so  nouveau_vieux_dri.so  r200_dri.so  r600_dri.so    radeonsi_dri.so   swrast_dri.so       virtio_gpu_dri.so
i965_dri.so  nouveau_dri.so     nvidia_drv_video.so   r300_dri.so  radeon_dri.so  s3g_drv_video.so  vdpau_drv_video.so  vmwgfx_dri.so
```
Which does contain the offending radeonsi_dri.so

So I see the issue and will try some symlinks later today to fix it, but I thought you guys might want to know

Kernal: 4.15.15-1-ARCH
GPU: AMD FuryX
No other known issues with programs failing to launch from similar opengl/dri/gpu issues, though library versioning is a common issue.

**Comment by yairchu** [comment]
Does [`GLFW-b-demo`](https://hackage.haskell.org/package/GLFW-b-demo) work on your system?

**Comment by VegaDeftwing** [comment]
AFAIK GLFW-b-demo is installed on arch as glxgears, and it does run fine

**Comment by ysangkok** [comment]
glxgears is in mesa-demos, i don't think it is the same

**Comment by yairchu** [comment]
@VegaDeftwing I think that while it may look and behave the same when it works, they are not the same.

`GLFW-b-demo` is an implementation of it in Haskell using the GLFW library, which are the same tools we use for Lamdu, so whether it works would provide relevant feedback for this issue.

**Comment by VegaDeftwing** [comment]
Yeah, it appears that ysangkok was correct. I'm working on it right now. apparently haskell-glfw wasn't installed on my system, though even when trying to symlink the libs it didn't work, which is strange.

**Comment by yairchu** [comment]
> apparently haskell-glfw wasn't installed on my system

It may not need to be installed.
`haskell-glfw` seems to be an arch-linux package for the hackage package [GLFW](http://hackage.haskell.org/package/GLFW), while we use the package [GLFW-b](https://hackage.haskell.org/package/GLFW-b).. This is indeed some confusing naming scheme but iirc at least at the time the GLFW package didn't work for us and GLFW-b seemed to be the working option...

**Comment by VegaDeftwing** [comment]
You'll have to forgive me, while I've done some haskell stuff, it's very very limited so I'm not 100% sure what I'm doing. I ran `cabal install glfw-b `and it finished successfully, but I'm still getting the same issue when trying to launch lamdu

**Comment by yairchu** [comment]
You are facing a runtime issue with Lamdu (not a build problem).

So building `glfw-b` won't tell you if this is a problem with Lamdu's code or a runtime problem with using `glfw-b`.

What I suggested is that you try **running** (not just building) `GLFW-b-demo` and see whether that has the same runtime problems. Knowing whether it has those same problems or not will help us pinpoint the issue..

**Comment by VegaDeftwing** [comment]
An hour of banging my head into my desk later the solution is
`export LD_LIBRARY_PATH=/usr/lib; lamdu`
which makes sense since as per the output above I already had all the libraries in my system. Though, obviously it would be nice if this wasn't necessary, so you may want to change something to work around different environments/systems.
