### ISSUE TITLE
Please clearly show holes

### ISSUE THREAD

**Issue by bjorn3** [lamdu/lamdu#96]
As a new user I accidentally created several holes (function call with hole as arg) without knowing it.

**Comment by Peaker** [comment]
@bjorn3 Thanks for the feedback!

We were pondering how it would be best to emphasize holes without overwhelming the UI.

Do you have any input on what would make the holes existence clearer?

**Comment by Peaker** [comment]
We've considered that but thought it might be very visually noisy.

Perhaps if it is dimly colored it wouldn't be so bad

**Comment by bjorn3** [comment]
+1 for dimmed color

**Comment by Peaker** [comment]
Feedback solicited for branch https://github.com/lamdu/lamdu/tree/issues/96-question-mark-holes
![image](https://user-images.githubusercontent.com/48899/40590655-3111c5d2-620b-11e8-9218-2859dddd7a7f.png)

@yairchu @bjorn3

**Comment by bjorn3** [comment]
Looks great!

**Comment by yairchu** [comment]
How about this option:

<img width="510" alt="screen shot 2018-05-28 at 22 00 19" src="https://user-images.githubusercontent.com/97606/40626651-a110de6a-62c2-11e8-9cee-2bdf819d66b2.png">

**Comment by Peaker** [comment]
Yours looks good!

Let's use it.

It feels like it emphasizes that the proportional fonts are ugly for operators there (different location for each right arg)
