### ISSUE TITLE
Native Deps Missing from Readme

### ISSUE THREAD

**Issue by JeffCarpenter** [lamdu/lamdu#98]
I just built Lamdu on my Ubuntu 18.04 install and had to install the following packages to get up and running:

* libglew-dev
* libglfw3-dev
* libglu1-mesa-dev
* libleveldb-dev

I also installed libfreetype6-dev because of a missing header file warning, although I don't know if it was necessary. Hope this helps.

**Comment by yairchu** [comment]
Some of these (`libglew-dev`, `libleveldb-dev`) already appear in the [Ubuntu instructions in the readme](https://github.com/lamdu/lamdu/blob/master/README.md#ubuntu)

I'm not sure about the difference between `libglfw3-dev` above and `libglfw-dev` from the readme, perhaps something in Ubuntu has changed?

**Comment by yairchu** [comment]
Have now added a new test to make sure the deps mentioned in our Travis configuration appear in the readme Ubuntu section. https://github.com/lamdu/lamdu/commit/5c255d4e56d2904d496f2cb8eddd51d37162a4ea

Perhaps it has to do with differences between Ubuntu 18.04 and Ubuntu 14.04 ([which is used in Travis CI](https://docs.travis-ci.com/user/reference/overview/#Container-based)).

**Comment by Peaker** [comment]
`libglew-dev`, `libleveldb-dev` are already in the install instructions.
`libglu1-mesa-dev` is a dependency of `libglew-dev`, so no need to manually install it.
`libglfw3-dev` is not a lamdu dependency.

**Comment by JeffCarpenter** [comment]
My mistake. Thanks for your replies, guys.
